(function(){
  if(!document.querySelector('link[href="../polish.css"]')){
    var polish=document.createElement('link');polish.rel='stylesheet';polish.href='../polish.css';document.head.appendChild(polish);
  }

  function addArchitecture(){
    if(document.getElementById('architecture'))return;
    var security=document.getElementById('security');if(!security)return;
    var section=document.createElement('section');section.className='architecture light-section';section.id='architecture';
    section.innerHTML='<div class="shell architecture-heading"><div class="section-index">06 / ARCHITEKTUR</div><div><span class="arch-kicker">Die entscheidende Frage ist nicht, welches Modell du nutzt.</span><h2>Die entscheidende Frage ist:<br><span>Was verlässt deine Schutzgrenze?</span></h2><p class="large-copy">Psoydo hält Originaldaten, Zuordnung und Rückübersetzung dort, wo du sie kontrollierst. Externe KI-Systeme erhalten nur den pseudonymisierten Arbeitskontext.</p></div></div><div class="shell architecture-board reveal"><div class="arch-zone trusted-zone"><div class="arch-zone-head"><span>DEINE UMGEBUNG</span><b>VERTRAUENSZONE</b></div><div class="arch-card original-card"><small>01</small><strong>Originaldaten</strong><span>Verträge · HR · Tickets · Logs</span></div><div class="arch-card psoydo-card"><small>02</small><strong>Psoydo</strong><span>Erkennung · Mapping · Review</span></div><div class="arch-vault"><span class="vault-dot"></span><div><strong>Lokales Mapping</strong><small>Original ↔ Pseudonym</small></div><em>unter deiner Kontrolle</em></div></div><div class="arch-boundary"><span>DEINE SCHUTZGRENZE</span><i></i><i></i></div><div class="arch-zone external-zone"><div class="arch-zone-head"><span>KI-SYSTEM</span><b>FREI WÄHLBAR</b></div><div class="arch-card payload-card"><small>03</small><strong>Pseudonymisierter Kontext</strong><span>PERSON_041 · ORT_003 · UNTERNEHMEN_018</span></div><div class="arch-models"><span>GPT</span><span>Claude</span><span>Gemini</span><span>weitere</span></div><div class="arch-card result-card"><small>04</small><strong>KI-Ergebnis</strong><span>ohne Kenntnis der Originalidentitäten</span></div></div></div><div class="shell architecture-facts reveal"><div><span>01</span><strong>Originale verlassen die Zone nicht</strong><p>Die eigentlichen Identitäten bleiben in deiner Umgebung.</p></div><div><span>02</span><strong>Die Zuordnung bleibt kontrolliert</strong><p>Das Mapping zwischen Original und Pseudonym bleibt innerhalb deiner kontrollierten Umgebung.</p></div><div><span>03</span><strong>Das Modell bleibt austauschbar</strong><p>Du wählst die KI nach Eignung für den Use Case und nicht nach der Sensibilität der Identitäten.</p></div></div>';
    security.parentNode.insertBefore(section,security);
  }

  function addPIFTeaser(){
    if(document.getElementById('pif'))return;
    var usecases=document.getElementById('usecases');if(!usecases)return;
    var section=document.createElement('section');section.className='pif-home light-section';section.id='pif';
    section.innerHTML='<div class="shell pif-home-grid"><div class="section-index">04 / PIF</div><div class="pif-home-copy"><span class="pif-kicker">Psoydo Intelligence Framework</span><h2>Pseudonymisierung ist kein<br><span>Suchen &amp; Ersetzen.</span></h2><p class="large-copy">Ein Begriff ist erst im Kontext eindeutig. Ein Name kann eine Person, ein Unternehmen, ein Ort oder gar nichts Schützenswertes sein. PIF verbindet Erkennung, Revision, Ursachenanalyse und menschliche Freigabe zu einem kontrollierten Lernkreislauf.</p><a class="text-link dark" href="technologie.html">Warum PIF anders arbeitet <span>↗</span></a></div></div><div class="shell pif-loop reveal"><div class="pif-stage"><small>01</small><strong>PFDI + Pipeline</strong><span>erkennen &amp; pseudonymisieren</span></div><div class="pif-arrow">→</div><div class="pif-stage"><small>02</small><strong>Revision</strong><span>Fehler sichtbar machen</span></div><div class="pif-arrow">→</div><div class="pif-stage"><small>03</small><strong>Verstehen</strong><span>Ursache statt Symptom</span></div><div class="pif-arrow">→</div><div class="pif-stage accent"><small>04</small><strong>Rückspielung</strong><span>nächster Durchlauf wird besser</span></div></div><div class="shell pif-principle reveal"><span class="mono">ERFOLGSMASSSTAB</span><p>Die Kontrolle ist nicht dann gut, wenn sie viel findet.<br><strong>Sondern wenn sie immer weniger finden muss.</strong></p></div>';
    usecases.parentNode.insertBefore(section,usecases);
  }

  function setNav(nav,mobile){
    if(nav){nav.innerHTML='<a href="#product">Produkt</a><a href="technologie.html">Technologie</a><a href="#usecases">Anwendungsfälle</a><a href="#security">Sicherheit</a><a href="#deployment">Betrieb</a>';}
    if(mobile){mobile.innerHTML='<a href="#product">Produkt</a><a href="technologie.html">Technologie</a><a href="#usecases">Anwendungsfälle</a><a href="#architecture">Architektur</a><a href="#security">Sicherheit</a><a href="#deployment">Betrieb</a><a href="#register">Registrieren</a>';}
  }

  function polishCopy(){
    setNav(document.querySelector('.desktop-nav'),document.querySelector('.mobile-menu'));
    var eyebrow=document.querySelector('.hero .eyebrow');if(eyebrow)eyebrow.innerHTML='<span class="signal"></span> Schutzschicht für Enterprise AI';
    var lead=document.querySelector('.hero-lead');if(lead)lead.innerHTML='Psoydo trennt Identität von Kontext, <strong>bevor</strong> sensible Inhalte ein externes KI-System erreichen. So kann dein Unternehmen leistungsfähige Modelle nutzen, ohne echte Personen- und Unternehmensbezüge offenzulegen.';
    var proof=document.querySelectorAll('.proof-row span');if(proof.length>=3){proof[0].textContent='Originaldaten bleiben lokal';proof[1].textContent='Zuordnung unter eigener Kontrolle';proof[2].textContent='KI frei wählbar';}
    var bottom=document.querySelectorAll('.hero-bottom p');if(bottom.length>=2){bottom[0].textContent='Die leistungsfähigsten Modelle sind längst da.';bottom[1].innerHTML='Was fehlt, ist eine <strong>sichere Datengrenze.</strong>';}
    var sidebar=document.querySelectorAll('.product-sidebar button');['Pre-Flight','Revision','Fälle','Audit'].forEach(function(t,i){if(sidebar[i])sidebar[i].textContent=t});
    var win=document.querySelector('.window-bar em');if(win)win.textContent='PIF · lokale Verarbeitung';
    var cases=document.querySelectorAll('.case-card p');if(cases.length>=3){cases[0].textContent='2.400 Kunden- und Lieferantenverträge mit Claude oder GPT analysieren. Namen, Ansprechpartner und andere personenbezogene Bezüge bleiben dabei innerhalb der eigenen Schutzgrenze.';cases[1].textContent='Ein Jahr Mitarbeitergespräche, Feedback und HR-Dokumentation gemeinsam auswerten. Das Modell erkennt Muster, ohne zu erfahren, welche reale Person hinter PERSON_041 steckt.';cases[2].textContent='SIEM-Meldungen, Tickets und technische Logs modellübergreifend korrelieren. Nutzer-, IP- und Systembezüge bleiben konsistent analysierbar, ohne reale Zuordnungen offenzulegen.';}
    var ui=document.querySelector('#usecases .section-index');if(ui)ui.textContent='05 / ANWENDUNGSFÄLLE';
    var sec=document.getElementById('security');if(sec){
      var idx=sec.querySelector('.section-index');if(idx)idx.textContent='07 / SECURITY BY ORIGIN';
      var h2=sec.querySelector('h2');if(h2)h2.textContent='Vertrauen braucht keinen Perfektionsclaim.';
      var sp=sec.querySelector('.sticky-copy .large-copy');if(sp)sp.textContent='Psoydo ist darauf ausgelegt, Fehler nicht zu verstecken, sondern sichtbar und bearbeitbar zu machen. Mehrere Kontrollstufen und der bewusste Sichtabgleich halten den Menschen in der Verantwortung.';
      var list=sec.querySelector('.security-list');if(list)list.innerHTML='<article><span>01</span><div><h3>Local-first</h3><p>Erkennung, Mapping und Rückübersetzung können innerhalb deiner eigenen Umgebung bleiben.</p></div></article><article><span>02</span><div><h3>Konsistenter Kontext</h3><p>Gleiche Entitäten bleiben innerhalb eines Falls konsistent zuordenbar, damit Beziehungen für die Analyse erhalten bleiben.</p></div></article><article><span>03</span><div><h3>Mehrschichtige Revision</h3><p>Trefferlisten, Risikokandidaten und OCR-Kandidaten machen mögliche Fehler sichtbar, messbar und gezielt prüfbar.</p></div></article><article><span>04</span><div><h3>Sichtabgleich</h3><p>Vor der finalen Freigabe bleibt eine bewusste menschliche Kontrollinstanz bestehen. Sie ist Sicherheitsnetz, nicht Ersatz für gute Erkennung.</p></div></article><article><span>05</span><div><h3>Nachvollziehbare Prozesse</h3><p>Verarbeitungsschritte und Freigaben können dokumentiert werden und damit revisionsfähige Gesamtprozesse unterstützen.</p></div></article>';
    }
    var dep=document.getElementById('deployment');if(dep){var di=dep.querySelector('.section-index');if(di)di.textContent='08 / BETRIEB';}
    var reg=document.getElementById('register');if(reg){var ri=reg.querySelector('.section-index');if(ri)ri.textContent='09 / REGISTRIERUNG';var rh=reg.querySelector('.register-copy h2');if(rh)rh.innerHTML='Psoydo für dein Unternehmen<br><span>registrieren.</span>';var rp=reg.querySelector('.register-copy > p');if(rp)rp.textContent='Kein Newsletter und keine Warteliste. Du registrierst dein Unternehmen mit einem konkreten KI-Use-Case. Wir prüfen, welche Betriebsform und welcher Integrationsweg dazu passen.';var pts=reg.querySelector('.registration-points');if(pts)pts.innerHTML='<span><i>1</i> Organisation registrieren</span><span><i>2</i> Use Case einordnen</span><span><i>3</i> Technischen nächsten Schritt festlegen</span>';if(pts&&!reg.querySelector('.registration-note')){var note=document.createElement('div');note.className='registration-note';note.innerHTML='<strong>Was danach passiert</strong><span>Wir melden uns mit einer konkreten Einschätzung statt mit einer automatisierten Sales-Sequenz.</span>';pts.insertAdjacentElement('afterend',note);}}
    var footer=document.querySelector('.footer-bottom div');if(footer&&!footer.querySelector('a[href="technologie.html"]')){var a=document.createElement('a');a.href='technologie.html';a.textContent='Technologie';footer.insertBefore(a,footer.firstChild);}
  }

  addArchitecture();addPIFTeaser();polishCopy();
  var header=document.querySelector('.site-header');function onScroll(){if(header)header.classList.toggle('scrolled',window.scrollY>20)}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
  var toggle=document.querySelector('.menu-toggle'),menu=document.querySelector('.mobile-menu');if(toggle&&menu){toggle.addEventListener('click',function(){var open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open))});menu.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true')})})}
  if('IntersectionObserver' in window){var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(function(el){io.observe(el)})}else{document.querySelectorAll('.reveal').forEach(function(el){el.classList.add('visible')})}
  function initTF(){var c=document.getElementById('tf-container');if(!c)return;if(!window.tf||!window.tf.createWidget){return setTimeout(initTF,200)}c.innerHTML='';window.tf.createWidget('01KVRJN19YZ8J86JFQYX9N09QG',{container:c,hideHeaders:true,hideFooter:true,inlineOnMobile:true})}initTF();
  var box=document.getElementById('consent'),KEY='psoydo-consent-v2';if(!box)return;function show(){box.classList.add('show');box.setAttribute('aria-hidden','false')}function hide(){box.classList.remove('show');box.setAttribute('aria-hidden','true')}function loadAds(){if(document.getElementById('google-gtag'))return;var s=document.createElement('script');s.id='google-gtag';s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=AW-18355213487';document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config','AW-18355213487')}
  var stored=null;try{stored=localStorage.getItem(KEY)}catch(e){}if(stored==='granted')loadAds();else if(stored!=='denied')setTimeout(show,900);var yes=document.getElementById('consent-accept'),no=document.getElementById('consent-decline'),reopen=document.getElementById('consent-reopen');if(yes)yes.addEventListener('click',function(){try{localStorage.setItem(KEY,'granted')}catch(e){}loadAds();hide()});if(no)no.addEventListener('click',function(){try{localStorage.setItem(KEY,'denied')}catch(e){}hide()});if(reopen)reopen.addEventListener('click',show);
})();
